manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cfergeau
      url-base: https://github.com/cfergeau
    - name: NuclearSquid
      url-base: https://github.com/Nuclear-Squid
    - name: rloutier
      url-base: https://github.com/rloutier
#    - name: rschenk
#      url-base: https://github.com/rschenk
    - name: iten828
      url-base: https://github.com/iten828
  projects:
    - name: zmk
      remote: zmkfirmware
      # Pin ZMK to the latest board fix of the `main` branch on 2026-06-13.
      # https://github.com/OneDeadKey/zmk-config-aekeynox/pull/67
      #revision: 9917e2f1371d5bb051bf8eb782c1297db41d742b
      revision: v0.3
      import: app/west.yml
    - name: zmk-keyboard-quacken
      remote: NuclearSquid
      revision: zmk-main
    - name: zmk-config-totem
      remote: cfergeau
      revision: zmk-module
      remote: rloutier
      revision: main
#    - name: zmk-keyboard-re-gret
#      remote: rschenk
#      revision: main
    - name: temper-zmk-config
      remote: iten828
      revision: enhancements
  self:
    path: config
